// Auto-generated boost descriptions for Sunflower Land Collectibles & Wearables

const ITEM_BOOSTS = {
  "stone beetle": "+0.1 Stone",
  "anemone flower": "+1 Fishing minigame attempt",
  "salt crystal flower": "5% chance for +1 Flower",
  "goblin crown": "+25% FLOWER & Coin Deliveries\n+10% Marks",
  "pet bowls": "+10 Pet XP per food request.",
  "karkinos": "+0.1 Cabbage\nDisabled if Cabbage Boy Active",
  "speed chicken": "-10% Chicken Sleep Time",
  "flamingo chicken": "-2.5% Chicken Sleep Time",
  "victoria sisters": "+20% Pumpkin",
  "easter bunny": "+20% Carrot",
  "purple trail": "+0.2 Eggplant",
  "sleepy chicken": "Chickens cannot get sick during autumn",
  "giant gold bone": "+2 Daily Cheers",
  "pharaoh chicken": "+1 daily Desert Dig attempt",
  "rich chicken": "+0.1 Egg",
  "pablo the bunny": "+0.1 Carrot",
  "fat chicken": "-10% Feed to Chicken",
  "obie": "-25% Eggplant Growth Time",
  "janitor chicken": "-5% chicken sleep time",
  "hungry hare": "Fermented Carrots 2x Bumpkin XP",
  "dino egg trophy": "Speed up with Coins instead of Gems (50 Coins/Gem, up to 20,000 Coins/day).",
  "spa sheep": "+5 Sheep XP from Animal Affection tools",
  "chicory": "10% Chance for +1 Flower",
  "desert rose": "10% Chance for +1 Flower",
  "squid chicken": "+0.1 Egg",
  "banana chicken": "+0.1 Banana",
  "reelmaster's chair": "+5 daily fishing reels",
  "nana": "-10% Banana Growth Time",
  "potent potato": "3% Chance of +10 Potato",
  "mermaid sheep": "-5% Sheep Feed",
  "alien chicken": "+0.1 Feathers",
  "lemon frog": "-25% Lemon Growth Time",
  "giant zucchini": "-50% Zucchini Plot Growth Time",
  "mushroom house": "+0.2 Wild Mushroom",
  "rice panda": "+0.25 Rice",
  "radical radish": "3% Chance of +10 Radish",
  "cabbage boy": "+0.25 Cabbage",
  "lady bug": "+0.25 Apple",
  "knight chicken": "+0.1 Oil",
  "oaken": "+0.25 Acorn",
  "maneki neko": "1 Free Food per Day",
  "astronaut sheep": "+0.1 Wool",
  "poppy": "+0.1 Corn",
  "stellar sunflower": "3% Chance of +10 Sunflower",
  "summer chicken": "Chickens cannot get sick during summer",
  "meerkat": "+5 daily Desert Digs attempts\n+1 Sand",
  "vinny": "+0.25 Grape",
  "soil krabby": "-10% Composter Compost Time",
  "giant yam": "+0.5 Yams",
  "peeled potato": "20% Chance for +1 Potato",
  "nurse sheep": "Sheep cannot get sick during summer",
  "reveling lemon": "+0.25 Lemon",
  "flower fox": "-10% Flower Growth Time",
  "cannonball": "-25% Tomato Growth Time",
  "foliant": "+0.2 Kale",
  "pink dolphin": "+1 Fish during Spring",
  "jellyfish": "+1 Fish during Summer",
  "squirrel monkey": "-50% Orange Growth Time",
  "tiki totem": "+0.1 Wood",
  "undead rooster": "+0.1 Egg",
  "queen cornelia": "+1 Corn\nAffects plots around (3x4)",
  "kernaldo": "-25% Corn Growth Time",
  "grain grinder": "+20% Bumpkin XP from Cakes",
  "lunar temple": "+1 help progress to player's monuments",
  "lemon shark": "+0.2 Lemons",
  "poseidon": "+1 Fish during Autumn",
  "alba": "50% Chance of +1 Basic Fish",
  "soybliss": "+1 Soybean",
  "spa cow": "+0.1 Milk",
  "nancy": "-15% Crop Growth Time\nDisabled if Scarecrow or Kuebiko Active",
  "observatory": "+5% Bumpkin XP",
  "frozen cow": "Cows cannot get sick during winter",
  "el pollo veloz": "-2h Chicken Sleep Time",
  "rooster": "2x Chance of Mutant Chicken",
  "freya fox": "+0.5 Pumpkin",
  "swiss whiskers": "+500 Bumpkin XP from Cheese Recipes",
  "mammoth": "-25% Cow Sleep Time",
  "battle fish": "+0.05 Oil",
  "tunnel mole": "+0.25 Stone",
  "lunar calendar": "-10% Crop Growth Time",
  "baby cow": "+10 cow xp from animal affection tools",
  "ayam cemani": "+0.2 Egg",
  "super star": "+1 Fish during Winter",
  "tin turtle": "+0.1 Stone\nAffects plots around (3x3)",
  "fruit tune box": "-20% Fruit Patch Growth Time",
  "skill shrimpy": "+20% Bumpkin XP from Fish",
  "maximus": "+1 Eggplant",
  "crim peckster": "+0.1 Crimstone",
  "frozen sheep": "Sheep cannot get sick during winter",
  "carrot sword": "4x Chance of Mutant Crop",
  "speed trap": "-20% Trap Pot time",
  "heart of davy jones": "+20 daily Desert Dig attempts",
  "king of bears": "+0.25 Honey per Full Beehive",
  "rock golem": "10% Chance of +2 Stone",
  "longhorn cowfish": "+0.2 Milk",
  "genie lamp": "Grants 3 Wishes from the Wish list",
  "hungry caterpillar": "Free Flower Seeds",
  "nautilus": "+5 daily fishing reels",
  "rocky the mole": "+0.25 Iron",
  "giant turnip": "-50% Turnip Growth Time",
  "black bearry": "+1 Blueberry",
  "moo-ver": "+0.25 Leather",
  "cabbage girl": "-50% Cabbage Plot Growth Time",
  "mysterious parsnip": "-50% Parsnip Growth Time",
  "woody the beaver": "+20% Wood\nDisabled if Apprentice Beaver or Foreman Beaver Active",
  "knowledge crab": "Double Sprout Mix Boost Effect",
  "crimstone clam": "-10% Crimstone recovery time\n10% chance for Crimstone to recover instantly",
  "tomato clown": "-50% Tomato Growth Time",
  "humming bird": "20% Chance for +1 Flower",
  "dr cow": "5% less feeding cost for cows",
  "grape granny": "+1 Grape",
  "toxic tuft": "+0.1 Merino Wool",
  "sir goldensnout": "+0.5 crop yield\nAffects plots around (4x4)",
  "gnome": "+10 yield to medium/advanced crops\nAffects plot below\nRequires Clementine & Cobalt",
  "scarecrow": "-15% Crop Growth Time\n+20% Crop Yield\nDisabled if Kuebiko Active",
  "giant onion": "+3 Onions",
  "cluckulator": "-25% Feed to Chicken",
  "lemon tea bath": "-50% Lemon Growth Time",
  "giant kale": "+2 Kale",
  "giant artichoke": "+2 Artichokes",
  "tomato bombard": "+1 Tomato",
  "wood nymph wendy": "+0.2 Wood",
  "summer guardian": "Summer Disaster Protection\nBlessed Summer Events",
  "sheaf of plenty": "+2 Barley",
  "mootant": "+0.1 Leather",
  "nugget": "+0.25 Gold",
  "winter guardian": "Winter Disaster Protection\nBlessed Winter Events",
  "navigation table": "+100% Map Piece Odds",
  "autumn guardian": "Autumn Disaster Protection\nBlessed Autumn Events",
  "deep sea slug": "+5 daily fishing reels\n+1 Worm from Composting",
  "camel": "+1 Sand\n+30% Treasure Sale Price",
  "spring guardian": "Spring Disaster Protection\nBlessed Spring Events",
  "crimson carp": "+0.05 Crimstone",
  "farm dog": "-25% Sheep Sleep Time",
  "apprentice beaver": "+20% Wood\n-50% Tree Recovery Time\nDisabled if Foreman Beaver Active",
  "walrus": "+1 Fish",
  "chicken coop": "+1 Egg\n+5 Base Chickens\n+5 Max Chickens per Hen House Upgrade",
  "golden cauliflower": "+100% Cauliflower",
  "groovy gramophone": "-50% Growth Time in Crop Machine",
  "magma stone": "-15% Lava Pit Time\n+0.15 Obsidian",
  "barn blueprint": "+5 Base Barn Animals\n+5 Max Barn Animals per Upgrade",
  "queen bee": "+1 Honey Production Speed",
  "royal crab pot": "Trap without Trap Pots",
  "hoot": "+0.5 Wheat, Radish, Kale, Rice, Barley",
  "crab house": "+2 Crustacean yield",
  "iron idol": "+1 Iron",
  "obsidian turtle": "+0.5 Obsidian",
  "golden sheep": "Feed Sheeps for free!",
  "turbo sprout": "-50% Growth Time in Greenhouse",
  "quarry": "Mine stone without pickaxes",
  "gold egg": "Feed Chickens for free",
  "kuebiko": "-15% Crop Growth Time\n+20% Crop Yield\nFree Seeds",
  "emerald turtle": "+0.5 Stone, Iron, Gold (AOE 3x3)\nAffects plots around (3x3)",
  "pharaoh gnome": "+2 Greenhouse Produce",
  "foreman beaver": "+20% Wood\n-50% Tree Recovery Time\nChop Trees without Axes",
  "grinx's hammer": "Halves expansion costs",
  "christmas tree": "Free Gift at Christmas",
  "golden cow": "Feed cows for free!",
  "walrus onesie": "+5 Pet Energy",
  "red pepper onesie": "-25% Red Pepper Growth Time",
  "shrimp onesie": "+1 random fish every 15th reel",
  "turd topper": "+1 Fertiliser from Composters",
  "tofu mask": "+0.1 Soybean",
  "eggplant onesie": "+0.1 Eggplant",
  "architect ruler": "-25% Crafting Box Time",
  "ladybug suit": "-25% Onion Seed coin cost",
  "white sheep onesie": "+0.25 Wool",
  "sunflower amulet": "+10% Sunflower",
  "carrot amulet": "-20% Carrot Plot Growth time",
  "banana onesie": "-20% Banana Growth Time",
  "dream scarf": "-20% Sheep Sleep Time",
  "olive royalty shirt": "+0.25 Olive",
  "bee suit": "+0.1 Honey per Full Beehive",
  "corn onesie": "+0.1 Corn",
  "chef apron": "+20% Cake Delivery Profit",
  "saw fish": "+5 daily fishing reels\n+1 Worm from Composting",
  "beetroot amulet": "+20% Beetroot",
  "mushroom hat": "+0.1 Wild Mushroom",
  "camel onesie": "+0.1 Fruit Patch Yield",
  "beekeeper hat": "+0.2 Honey Production Speed",
  "crab trap": "+1 Crab when digging or drilling",
  "crimstone armor": "+0.1 Crimstones",
  "deep sea salt cave background": "+5 Salt per harvest",
  "grape pants": "+0.2 Grapes",
  "banana amulet": "+0.5 Bananas",
  "broccoli hat": "-50% Broccoli Plot Growth Time",
  "chicken suit": "+1 Feather",
  "bubble aura": "-20% Fish Market processing time\n20% chance for +1 yield from Fish Processing",
  "medic apron": "-50% Medicine to heal animals",
  "merino jumper": "+1 Merino Wool",
  "olive shield": "+1 Olive",
  "corn silk hair": "+2 Corn",
  "oil can": "+2 Oil",
  "crab hat": "+1 treasure when fishing",
  "victoria's apron": "33% chance next reset is free after feeding pet fully.",
  "pistol shrimp": "20% chance to get +1 crustacean yield",
  "beast shoes": "Pet XP +100/+250 (Med/Hard)",
  "non la hat": "+1 Rice",
  "squirrel onesie": "+1 Acorn",
  "sol & luna": "-50% Crafting Box Time",
  "paw shield": "+25% Faction Pet Satiation and Marks Awarded",
  "hornet mask": "2x base Bee Swarm chance",
  "milk apron": "+0.5 Milk",
  "parsnip": "+20% Parsnip",
  "sunflower shield": "Free Sunflower Seeds",
  "crimstone amulet": "-20% Crimstone Cooldown Time",
  "golden spatula": "+10% Bumpkin XP",
  "lemon shield": "+1 Lemon",
  "frozen heart": "+1 Yield to Winter Plot Crop in Winter",
  "pickaxe shark": "-15% Gold recovery time\n10% chance for gold to recover instantly",
  "blossom ward": "+1 Yield to Spring Plot Crop in Spring",
  "oil gallon": "+5 Oil",
  "black sheep onesie": "+2 Wool",
  "training whistle": "+1 Leather",
  "oracle syringe": "Heal animals for free",
  "solflare aegis": "-50% Plot Crop Time in Summer",
  "honeycomb shield": "+1 Honey per Full Beehive",
  "sickle": "+2 Wheat",
  "green amulet": "Chance 10x Crops",
  "flower crown": "-50% Flower Growth Time",
  "dev wrench": "-50% Oil Regeneration Time",
  "cattlegrim": "+0.25 Animal Produce",
  "oil overalls": "+10 Oil",
  "obsidian necklace": "-50% Lava Pit Time",
  "autumn's embrace": "-50% Plot Crop Time in Autumn",
  "cowbell necklace": "+2 Milk",
  "crimstone hammer": "+2 Crimstones on 5th mine",
  "lava swimwear": "-50% Lava Pit resources",
  "infernal bullwhip": "-50% Feed to Barn Animal",
  "ancient rod": "Cast without rod",
  "luna's hat": "-50% Cooking Time",
  "pan": "+25% Bumpkin XP",
  "crimstone spikes hair": "Mine crimstone without Gold Pickaxes",
  "paw aura": "Feed pets for free",
  "angel wings": "30% Chance of Instant Crops",
  "infernal drill": "Drill Oil without Oil Drill",
  "ancient shovel": "Dig treasure without Sand Shovel",
  "devil wings": "30% Chance of Instant Crops",
  "infernal pitchfork": "+3 Crops"
};

function getItemBoost(name) {
  if (!name || typeof name !== 'string') return '';
  const key = name.toLowerCase().trim();
  if (ITEM_BOOSTS[key]) return ITEM_BOOSTS[key];
  const unbracketed = key.replace(/^\[.*?\]\s*/, '').trim();
  if (ITEM_BOOSTS[unbracketed]) return ITEM_BOOSTS[unbracketed];
  return '';
}

module.exports = {
  ITEM_BOOSTS,
  getItemBoost
};
